name: CI

on:
  push:
    branches:
      - master
  pull_request: {}

concurrency:
  group: ci-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: "Tests"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: wyvox/action-setup-pnpm@v3
        with:
          node-version: 18.x
          args: "--frozen-lockfile"
      - name: Run tests
        run: pnpm test
